// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: storezhang/transfer/type.proto

package transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 类型
type Type int32

const (
	// 未设置，不要使用
	Type_TYPE_UNKNOWN Type = 0
	// 纯Http
	Type_HTTP Type = 1
	// 文件传输
	Type_FTP Type = 2
	// 阿里云对象存储
	Type_OSS Type = 3
	// 腾讯云对象存储
	Type_COS Type = 4
	// 本地
	Type_LOCAL Type = 15
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "TYPE_UNKNOWN",
		1:  "HTTP",
		2:  "FTP",
		3:  "OSS",
		4:  "COS",
		15: "LOCAL",
	}
	Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"HTTP":         1,
		"FTP":          2,
		"OSS":          3,
		"COS":          4,
		"LOCAL":        15,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_storezhang_transfer_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_storezhang_transfer_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_storezhang_transfer_type_proto_rawDescGZIP(), []int{0}
}

var File_storezhang_transfer_type_proto protoreflect.FileDescriptor

var file_storezhang_transfer_type_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x2a, 0x48, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x54, 0x50,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x53, 0x53, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x43,
	0x4f, 0x53, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x0f, 0x42,
	0x45, 0x0a, 0x18, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61,
	0x6e, 0x67, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a,
	0x68, 0x61, 0x6e, 0x67, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x3b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storezhang_transfer_type_proto_rawDescOnce sync.Once
	file_storezhang_transfer_type_proto_rawDescData = file_storezhang_transfer_type_proto_rawDesc
)

func file_storezhang_transfer_type_proto_rawDescGZIP() []byte {
	file_storezhang_transfer_type_proto_rawDescOnce.Do(func() {
		file_storezhang_transfer_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_storezhang_transfer_type_proto_rawDescData)
	})
	return file_storezhang_transfer_type_proto_rawDescData
}

var file_storezhang_transfer_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storezhang_transfer_type_proto_goTypes = []interface{}{
	(Type)(0), // 0: storezhang.transfer.Type
}
var file_storezhang_transfer_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storezhang_transfer_type_proto_init() }
func file_storezhang_transfer_type_proto_init() {
	if File_storezhang_transfer_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storezhang_transfer_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storezhang_transfer_type_proto_goTypes,
		DependencyIndexes: file_storezhang_transfer_type_proto_depIdxs,
		EnumInfos:         file_storezhang_transfer_type_proto_enumTypes,
	}.Build()
	File_storezhang_transfer_type_proto = out.File
	file_storezhang_transfer_type_proto_rawDesc = nil
	file_storezhang_transfer_type_proto_goTypes = nil
	file_storezhang_transfer_type_proto_depIdxs = nil
}
